# Generated by Django 5.1 on 2024-10-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('mangalist', '0006_rename_categoria_manga_categoria_manga_generos'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='favoritos',
            field=models.ManyToManyField(to='mangalist.manga', verbose_name='Users'),
        ),
    ]
