# Generated by Django 5.1 on 2024-10-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_perfil_favoritos'),
        ('mangalist', '0006_rename_categoria_manga_categoria_manga_generos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='favoritos',
            field=models.ManyToManyField(related_name='Users', to='mangalist.manga', verbose_name='Favoritos'),
        ),
    ]
