# Generated by Django 5.1 on 2024-09-14 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=95)),
                ('last_name', models.CharField(blank=True, max_length=95, null=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=55, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=55, unique=True)),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
            },
        ),
        migrations.CreateModel(
            name='Ilustrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=95)),
                ('last_name', models.CharField(blank=True, max_length=95, null=True)),
            ],
            options={
                'verbose_name': 'Ilustrador',
                'verbose_name_plural': 'Ilustradores',
            },
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('volumes', models.IntegerField(blank=True, null=True)),
                ('capitulos', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('l', 'Em lançamento'), ('h', 'Em hiato'), ('f', 'Finalizado')], default='f', max_length=1)),
                ('data_lancamento', models.DateField()),
                ('data_encerramento', models.DateField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mangas', to='mangalist.autor')),
            ],
            options={
                'verbose_name': 'Mangá',
                'verbose_name_plural': 'Mangás',
            },
        ),
    ]
