# Generated by Django 5.1 on 2024-09-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangalist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='data_encerramento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de encerramento'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='data_lancamento',
            field=models.DateField(verbose_name='Data de lançamento'),
        ),
    ]
