# Generated by Django 5.1 on 2024-09-15 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangalist', '0002_alter_manga_data_encerramento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='ilustrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ilustrador', to='mangalist.ilustrador'),
        ),
    ]
