# Generated by Django 5.1 on 2024-09-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangalist', '0003_manga_ilustrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='last_name',
            field=models.CharField(blank=True, default=' ', max_length=95),
        ),
    ]
