# Generated by Django 5.1 on 2024-09-26 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangalist', '0004_alter_autor_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='Categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='catManga', to='mangalist.categoria'),
        ),
        migrations.AlterField(
            model_name='ilustrador',
            name='last_name',
            field=models.CharField(blank=True, default=' ', max_length=95),
        ),
    ]
